name: Build and Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      dockerhub_user:
        required: true
      dockerhub_token:
        required: true
        
jobs:
  docker_build:
    name: Build and Push to Docker Registry

    runs-on: ubuntu-latest

    # if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          if [[ -z "${{ inputs.tag }}" ]]
          then 
            echo "final-tag=latest" >> $GITHUB_ENV
          else
            echo "final-tag=${{ inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - name: Build and push service docker
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: fin3technologies/${{ inputs.image_name }}:${{ inputs.tag }}