name: Build and Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      fin3_github_token:
        required: true
      dockerhub_user:
        required: true
      dockerhub_token:
        required: true
      aws_fin3_account_id:
        required: true
      fin3_docker_sign_passwd:
        required: true
      awskms_docker_image_sign_key:
        required: true
      aws_access_key:
        required: true
      aws_secret_key:
        required: true
env:
  REGISTRY: fin3technologies
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.aws_fin3_account_id }}
jobs:
  docker_build:
    name: Build and Push to Docker Registry

    runs-on: ubuntu-latest

    # if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v2
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - name: Build and push service docker
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: fin3technologies/${{ inputs.image_name }}:${{ env.final_tag }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: us-east-1

      - name: cosign-installer
        uses: Fin3-Technologies-Inc/gh-action-cosign-installer@main
        
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.fin3_docker_sign_passwd }}
        run: |
          cosign sign --key ${{ secrets.awskms_docker_image_sign_key }} \
            -a "repo=${{ github.repository }}" \
            -a "auther=Fin3 Technologies Inc" \
            -a "ref=${{ github.sha }}" \
          ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ env.final_tag }}