name: Sonarscan
on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      fin3_github_token:
        required: true
jobs:
  sonarcloud:
    name: CodeScan (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
        run: gradle sonarqube -DsystemProp.sonar.host.url="https://sonarcloud.io" -Dsonar.host.url="https://sonarcloud.io" -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="fin3-technologies-inc"