name: Sonarscan
on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      fin3_github_token:
        required: true
      dockerhub_user:
        required: true
      dockerhub_token:
        required: true        
jobs:
  sonarcloud:
    name: CodeScan (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      
      - name: Execute Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.fin3_github_token }}
        run: ./gradlew build -x test

      - name: Test and SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          GITHUB_TOKEN: ${{ secrets.fin3_github_token }}
        run: ./gradlew test -i codeCoverageReport sonarqube -DsystemProp.sonar.host.url="https://sonarcloud.io" -Dsonar.host.url="https://sonarcloud.io" -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="fin3-technologies-inc"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
