name: Sonarscan
on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      fin3_github_token:
        required: true
jobs:
  sonarcloud:
    name: CodeScan (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
        run: |
          mvn -Dsonar.coverage.jacoco.xmlReportPaths=jacoco.xml -Dsonar.host.url="https://sonarcloud.io" clean verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}
          mvn clean install verify
          mvn sonar:sonar -Dsonar.host.url="https://sonarcloud.io" -Dsonar.login=${SONAR_TOKEN}