name: Build and Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      fin3_github_token:
        required: true
      dockerhub_user:
        required: true
      dockerhub_token:
        required: true
      fin3_docker_sign_priv_key:
        required: true
      fin3_docker_sign_passwd:
        required: true
env:
  REGISTRY: fin3technologies

jobs:  
  docker_build:
    name: Build and Push to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@Fin3-Technologies-Inc'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.fin3_github_token }}

      - name: Node install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.fin3_github_token }}

      - name: Build and push service docker
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: fin3technologies/${{ inputs.image_name }}:${{ env.final_tag }}

      - name: cosign-installer
        uses: Fin3-Technologies-Inc/gh-action-cosign-installer@main

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.fin3_docker_sign_priv_key }}

      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.fin3_docker_sign_passwd }}
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "auther=Fin3 Technologies Inc" \
            -a "ref=${{ github.sha }}" \
          ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ env.final_tag }}